export const FETCHED_SHOW_DETAILS = '@SHOW/FETCHED_DETAILS';
export const SHOW_DETAILS_FETCH_FAILED = '@SHOW/DETAILS_FETCH_FAILED';

export const FETCHED_EPISODE_DETAILS = '@EPISODE/FETCHED_DETAILS';
export const EPISODE_DETAILS_FETCH_FAILED = '@EPISODE/DETAILS_FETCH_FAILED';
export const FETCHING_EPISODE_DETAILS = '@EPISODE/FETCHING_DETAILS';

export const FETCHED_EPISODE_DETAILS_INFO = '@EPISODE/DETAILS_INFO_FETCHED';
export const FAILED_EPISODE_DETAILS_INFO = '@EPISODE/DETAILS_INFO_FAILED';